<?php

namespace Proxies\__CG__\WebVL\WebVillasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Villas extends \WebVL\WebVillasBundle\Entity\Villas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'size', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'rooms', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'restrooms', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'view', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'address', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'price', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'details', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'geox', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'geoy', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'idVillas', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'users', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'states');
        }

        return array('__isInitialized__', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'size', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'rooms', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'restrooms', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'view', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'address', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'price', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'details', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'geox', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'geoy', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'idVillas', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'users', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\Villas' . "\0" . 'states');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Villas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array());

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms($rooms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', array($rooms));

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', array());

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setRestrooms($restrooms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRestrooms', array($restrooms));

        return parent::setRestrooms($restrooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getRestrooms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRestrooms', array());

        return parent::getRestrooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setView($view)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setView', array($view));

        return parent::setView($view);
    }

    /**
     * {@inheritDoc}
     */
    public function getView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getView', array());

        return parent::getView();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetails($details)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetails', array($details));

        return parent::setDetails($details);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', array());

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeox($geox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeox', array($geox));

        return parent::setGeox($geox);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeox', array());

        return parent::getGeox();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeoy($geoy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeoy', array($geoy));

        return parent::setGeoy($geoy);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoy', array());

        return parent::getGeoy();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVillas()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdVillas();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVillas', array());

        return parent::getIdVillas();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsers(\WebVL\WebVillasBundle\Entity\Users $users = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', array($users));

        return parent::setUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', array());

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setStates(\WebVL\WebVillasBundle\Entity\States $states = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStates', array($states));

        return parent::setStates($states);
    }

    /**
     * {@inheritDoc}
     */
    public function getStates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStates', array());

        return parent::getStates();
    }

}
