<?php

namespace Proxies\__CG__\WebVL\WebVillasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AvailEquipment extends \WebVL\WebVillasBundle\Entity\AvailEquipment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'pool', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'gym', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'parking', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'sauna', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'id', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'villasVillas');
        }

        return array('__isInitialized__', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'pool', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'gym', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'parking', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'sauna', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'id', '' . "\0" . 'WebVL\\WebVillasBundle\\Entity\\AvailEquipment' . "\0" . 'villasVillas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AvailEquipment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPool($pool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPool', array($pool));

        return parent::setPool($pool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPool', array());

        return parent::getPool();
    }

    /**
     * {@inheritDoc}
     */
    public function setGym($gym)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGym', array($gym));

        return parent::setGym($gym);
    }

    /**
     * {@inheritDoc}
     */
    public function getGym()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGym', array());

        return parent::getGym();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', array($parking));

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', array());

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setSauna($sauna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSauna', array($sauna));

        return parent::setSauna($sauna);
    }

    /**
     * {@inheritDoc}
     */
    public function getSauna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSauna', array());

        return parent::getSauna();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVillasVillas(\WebVL\WebVillasBundle\Entity\Villas $villasVillas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVillasVillas', array($villasVillas));

        return parent::setVillasVillas($villasVillas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVillasVillas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVillasVillas', array());

        return parent::getVillasVillas();
    }

}
